# GNN + MLP, no visual info, iterative link prediction, pool by UPC

run_name: 0.2.2
num_epochs: 20
batch_size: 8
lr: 3e-4
weight_decay: 1e-5
num_workers: 0
accelerator: cpu
balanced_edge_sampling: True
a: 1.0
b: 0.5
model:
  use_visual_info: False
  aggregate_by_upc: True
  use_spatially_invariant_coords: False
  encoder_type: transformer
  encoder_settings:
    node_hidden_dim: 128
    num_layers: 2
  link_predictor_type: mlp
  link_predictor_settings:
    strategy: hadamard
    layer_widths: [128, 64]
dataset_dir: data/price-graphs-i
logging:
  use_wandb: True
  project_name: price-attribution
  log_dir: logs
  chkp_dir: chkp
