repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
        - id: ruff
          types_or: [ python, pyi ]
          args: [ --fix ]
        - id: ruff-format
          types_or: [ python, pyi ]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.txt$
    -   id: end-of-file-fixer
        exclude: \.txt$
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.4
    hooks:
      - id: uv-lock
