run_name: test_run
num_epochs: 2
batch_size: 2
lr: 3e-4
weight_decay: 1e-5
num_workers: 0
accelerator: cpu
a: 1.0
b: 2.0
balanced_edge_sampling: True
model:
  encoder_type: transformer
  encoder_settings:
    node_hidden_dim: 32
    num_layers: 2
  link_predictor_type: mlp
  link_predictor_settings:
    strategy: hadamard
    layer_widths: [32, 16]
dataset_dir: data/price-graphs-i
log_dir: logs
chkp_dir: chkp
