# GNN + MLP, no visual info, all-at-once link prediction, pool by UPC, spatially-invariant coords

run_name: 0.1.4
num_epochs: 20
batch_size: 8
lr: 3e-4
weight_decay: 1e-5
num_workers: 4
accelerator: gpu
balanced_edge_sampling: True
model:
  use_visual_info: False
  aggregate_by_upc: True
  use_spatially_invariant_coords: True
  encoder_type: transformer
  encoder_settings:
    node_hidden_dim: 128
    num_layers: 2
  link_predictor_type: mlp
  link_predictor_settings:
    strategy: hadamard
    layer_widths: [128, 64]
dataset_dir: data/price-graphs-ii
logging:
  use_wandb: True
  project_name: price-attribution
  log_dir: logs
  chkp_dir: chkp
