# Based on hparam analysis with SHAP after the random search, this
# should be the best configuration we can come up with to this point

accelerator: cpu
balanced_edge_sampling: false
batch_size: 8
dataset_dir: data/price-graphs-ii
gamma: 2.0
logging:
  chkp_dir: chkp
  log_dir: logs
  project_name: price-attribution
  use_wandb: true
lr: 0.0003
model:
  aggregate_by_upc: false
  encoder_settings:
    node_hidden_dim: 128
    num_layers: 2
  encoder_type: transformer
  initial_connection_strategy: nearest_below
  link_predictor_settings:
    layer_widths:
    - 128
    - 128
    - 64
    - 32
    pi: 0.5
    strategy: hadamard
  link_predictor_type: mlp
  use_spatially_invariant_coords: true
  use_visual_info: false
num_epochs: 20
num_workers: 0
run_name: '1110201'
weight_decay: 1.0e-05
