accelerator: cpu
balanced_edge_sampling: false
edge_deletion_only: true
batch_size: 8
dataset_dir: data/price-graphs-ii
gamma: 2.0
logging:
  chkp_dir: chkp
  log_dir: logs
  project_name: price-attribution
  use_wandb: true
lr: 0.0003
model:
  encoder_settings:
    node_hidden_dim: 128
    num_layers: 2
  encoder_type: transformer
  link_predictor_settings:
    layer_widths:
    - 128
    - 128
    - 64
    - 32
    pi: 0.5
    strategy: hadamard
  link_predictor_type: mlp
  initial_connection:
    method: seed_model
    seed_model:
      trn_config_path: configs/train/best_so_far.yaml
      chkp_path: chkp/best-so-far/best_loss.ckpt
  use_spatially_invariant_coords: true
  use_visual_info: false
num_epochs: 20
num_workers: 0
run_name: seed_1
weight_decay: 1.0e-05
